### ISSUE TITLE
Error is reported when num_works> 0

### ISSUE THREAD

**Issue by intense857** [VitjanZ/DRAEM#8]
TypeError: Caught TypeError in DataLoader worker process 0.
TypeError: 'NoneType' object is not subscriptable

**Comment by intense857** [comment]
Anaconda3\envs\pytorch\Lib\site-packages\imgaug\augmenters\color.py


        table_hue = cls._LUT_CACHE[0]
        table_saturation = cls._LUT_CACHE[1]


        # here  cls._LUT_CACHE is None, add this can solve the problem    
        if cls._LUT_CACHE is None:
            cls._LUT_CACHE = cls._generate_lut_table()
        table_hue = cls._LUT_CACHE[0]
        table_saturation = cls._LUT_CACHE[1]

**Comment by flyingtiger111** [comment]
> TypeError: Caught TypeError in DataLoader worker process 0. TypeError: 'NoneType' object is not subscriptable

Did you solve the problem? I meet it and I do not how to tackle.
