### ISSUE TITLE
Question about the requirement.txt

### ISSUE THREAD

**Issue by jiaq-liu** [VitjanZ/DRAEM#9]
The format of requirement is strange and can't be used as "pip install -r" or "conda create -n -f", may be a yaml file is more suitable?
I'll appreciate it if the available environment information provided.
Thanks a lot.

**Comment by jiaq-liu** [comment]
If anyone else has the same question, I think you can create conda environment with python3.8.
Then install pytorch, and pip install opencv-python==4.5.3.56 imgaug==0.4.0 sklearn==0.0.
That's enough.

**Comment by Xu-913** [comment]
good
